#General settings
date: "27/02/2019"
title: Claudia Witkowski
email: claudia.witkowski@mailbox.org
description: Claudia Witkowski is an economist focusing on effective development cooperation and finance.
cc: ""
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ['README.md']
url: "www.cwitkowski.de"
linkedin_username: claudiawitkowski
markdown: kramdown
remote_theme: academic


#Languages
langs: ["en", "de"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"
