#General settings
date: "24/12/2018"
title: Claudia Witkowski
email: claudia.witkowski@mailbox.org
description: Claudia Witkowski is an economist focusing on effective development cooperation and development finance. 
cc: ""
exclude: ['README.md']
url: "www.cwitkowski.de" 
linkedin_username: claudiawitkowski
markdown: kramdown
remote_theme: academic

  
#Languages
langs: ["en", "de"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"
      
      