#General settings
date: "06/03/2019"
title: Claudia Witkowski
email: claudia.witkowski@mailbox.org
description: Claudia Witkowski is an economist focusing on effective development cooperation and financing.
cc: ""
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ['README.md']
url: "www.cwitkowski.de"
linkedin_username: claudiawitkowski
markdown: kramdown
remote_theme: academic

gems:
  - jekyll-last-modified-at
  
#Languages
langs: ["en", "de"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"
